import { ToastContainer } from "react-toastify";
import "./globals.css";
import WhatsAppButton from "@/components/WhatApp/WhatsAppButton";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        cz-shortcut-listen="true"
        data-new-gr-c-s-check-loaded="14.1256.0"
        data-gr-ext-installed=""
      >
        {children}
        <WhatsAppButton />
        <ToastContainer />
      </body>
    </html>
  );
}
